// AUTO-GENERATED by scripts/gen_atomic_units.py — DO NOT EDIT BY HAND.
// Source: QCElemental v0.50.2, physical-constants context `CODATA2018`.
// Regenerate by running `python3 scripts/gen_atomic_units.py`.
// Generated on 2026-06-09.
//
// Each constant is the SI value of one atomic-unit quantity. Inverse-
// dimension factors (e.g. 1/length, 1/time, 1/pressure) are derived in
// Rust as reciprocals.

/// Bohr radius a_0  ->  meter
pub const LENGTH_BOHR_TO_M: f64 = 5.29177210903e-11;

/// electron rest mass m_e  ->  kilogram
pub const MASS_ME_TO_KG: f64 = 9.1093837015e-31;

/// elementary charge e  ->  coulomb
pub const CHARGE_E_TO_C: f64 = 1.602176634e-19;

/// Hartree E_h  ->  joule
pub const ENERGY_HARTREE_TO_J: f64 = 4.359744722207101e-18;

/// atomic time unit (hbar / E_h)  ->  second
pub const TIME_AU_TO_S: f64 = 2.4188843265857195e-17;

/// E_h / a_0  ->  newton
pub const FORCE_AU_TO_N: f64 = 8.238723498254079e-08;

/// E_h / a_0^3  ->  pascal
pub const PRESSURE_AU_TO_PA: f64 = 29421015696522.1;

/// E_h / k_B  ->  kelvin
pub const TEMPERATURE_AU_TO_K: f64 = 315775.0248040668;

/// a_0 / au-time  ->  m/s
pub const VELOCITY_AU_TO_M_PER_S: f64 = 2187691.2636411153;
