#!/usr/bin/env python3
"""
Generate src/units/atomic_constants.rs from QCElemental's CODATA-2018
physical-constants context.

Run this script when CODATA updates or when QCElemental's bundled
constants change. The generated file is committed to the repo so the
build does not depend on a Python toolchain.

Usage:
    python3 scripts/gen_atomic_units.py
"""

import datetime
from pathlib import Path

import qcelemental as qcel


CONTEXT_NAME = "CODATA2018"

# Each entry: (Rust const name, QCElemental "from" unit string, "to" unit string,
#              short comment for the generated file).
FACTORS = [
    ("LENGTH_BOHR_TO_M",            "bohr",                          "meter",          "Bohr radius a_0  ->  meter"),
    ("MASS_ME_TO_KG",               "electron_mass",                 "kg",             "electron rest mass m_e  ->  kilogram"),
    ("CHARGE_E_TO_C",               "elementary_charge",             "coulomb",        "elementary charge e  ->  coulomb"),
    ("ENERGY_HARTREE_TO_J",         "hartree",                       "joule",          "Hartree E_h  ->  joule"),
    ("TIME_AU_TO_S",                "atomic_unit_of_time",           "s",              "atomic time unit (hbar / E_h)  ->  second"),
    ("FORCE_AU_TO_N",               "hartree / bohr",                "newton",         "E_h / a_0  ->  newton"),
    ("PRESSURE_AU_TO_PA",           "hartree / bohr**3",             "pascal",         "E_h / a_0^3  ->  pascal"),
    ("TEMPERATURE_AU_TO_K",         "hartree / boltzmann_constant",  "kelvin",         "E_h / k_B  ->  kelvin"),
    ("VELOCITY_AU_TO_M_PER_S",      "bohr / atomic_unit_of_time",    "meter / second", "a_0 / au-time  ->  m/s"),
]


def main() -> None:
    pc = qcel.PhysicalConstantsContext(CONTEXT_NAME)
    qcel_version = qcel.__version__

    lines: list[str] = []
    lines.append("// AUTO-GENERATED by scripts/gen_atomic_units.py — DO NOT EDIT BY HAND.")
    lines.append(f"// Source: QCElemental v{qcel_version}, physical-constants context `{CONTEXT_NAME}`.")
    lines.append(f"// Regenerate by running `python3 scripts/gen_atomic_units.py`.")
    lines.append(f"// Generated on {datetime.date.today().isoformat()}.")
    lines.append("//")
    lines.append("// Each constant is the SI value of one atomic-unit quantity. Inverse-")
    lines.append("// dimension factors (e.g. 1/length, 1/time, 1/pressure) are derived in")
    lines.append("// Rust as reciprocals.")
    lines.append("")
    for name, frm, to, comment in FACTORS:
        value = pc.conversion_factor(frm, to)
        lines.append(f"/// {comment}")
        lines.append(f"pub const {name}: f64 = {value!r};")
        lines.append("")

    out_path = Path(__file__).resolve().parent.parent / "src" / "units" / "atomic_constants.rs"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path} ({len(FACTORS)} constants from QCElemental {qcel_version} / {CONTEXT_NAME})")


if __name__ == "__main__":
    main()
